local_tickers = [
    { "text": { "text": "Microsoft Corp - MSFT", "type": "plain_text" }, "value": "MSFT - 000789019" },    
    { "text": { "text": "Apple Inc - AAPL", "type": "plain_text" }, "value": "AAPL - 000320193" },
    { "text": { "text": "Amazon Com Inc - AMZN", "type": "plain_text" }, "value": "AMZN - 0001018724" },
    { "text": { "text": "Facebook Inc - FB", "type": "plain_text" }, "value": "FB - 0001326801" },
    { "text": { "text": "Berkshire Hathaway Inc - BRK", "type": "plain_text" }, "value": "BRK - 0001067983" },
    { "text": { "text": "Visa Inc - V", "type": "plain_text" }, "value": "V - 0001403161" },
    { "text": { "text": "Nvidia Corp - NVDA", "type": "plain_text" }, "value": "NVDA - 0001045810" },
    { "text": { "text": "Johnson & Johnson - JNJ", "type": "plain_text" }, "value": "JNJ - 000200406" },
    { "text": { "text": "Wal Mart Stores Inc - WMT", "type": "plain_text" }, "value": "WMT - 000104169" },
    { "text": { "text": "JPMorgan Chase & Co - JPM", "type": "plain_text" }, "value": "JPM - 00019617" },
    { "text": { "text": "Bank Of America Corp - BAC", "type": "plain_text" }, "value": "BAC - 00070858" },
    { "text": { "text": "Mastercard Inc - MA", "type": "plain_text" }, "value": "MA - 0001141391" },
    { "text": { "text": "Procter & Gamble Co - PG", "type": "plain_text" }, "value": "PG - 00080424" },
    { "text": { "text": "Walt Disney Co - DIS", "type": "plain_text" }, "value": "DIS - 0001001039" },
    { "text": { "text": "Adobe Systems Inc - ADBE", "type": "plain_text" }, "value": "ADBE - 000796343" },
    { "text": { "text": "Nike Inc - NKE", "type": "plain_text" }, "value": "NKE - 000320187" },
    { "text": { "text": "Pfizer Inc - PFE", "type": "plain_text" }, "value": "PFE - 00078003" },
    { "text": { "text": "Oracle Corp - ORCL", "type": "plain_text" }, "value": "ORCL - 0001341439" },
    { "text": { "text": "Coca-Cola Enterprises Inc - CCE", "type": "plain_text" }, "value": "CCE - 0001491675" },
    { "text": { "text": "Exxon Mobil Corp - XOM", "type": "plain_text" }, "value": "XOM - 00034088" },
    { "text": { "text": "Cisco Systems Inc - CSCO", "type": "plain_text" }, "value": "CSCO - 000858877" },
    { "text": { "text": "Verizon Communications Inc - VZ", "type": "plain_text" }, "value": "VZ - 000732712" },
    { "text": { "text": "Salesforce Com Inc - CRM", "type": "plain_text" }, "value": "CRM - 0001108524" },
    { "text": { "text": "Netflix Inc - NFLX", "type": "plain_text" }, "value": "NFLX - 0001065280" },
    { "text": { "text": "Intel Corp - INTC", "type": "plain_text" }, "value": "INTC - 00050863" },
    { "text": { "text": "Boeing Co - BA", "type": "plain_text" }, "value": "BA - 00012927" },
    { "text": { "text": "Starbucks Corp - SBUX", "type": "plain_text" }, "value": "SBUX - 000829224" },
    { "text": { "text": "American Express Co - AXP", "type": "plain_text" }, "value": "AXP - 0004962" },
    { "text": { "text": "Lockheed Martin Corp - LMT", "type": "plain_text" }, "value": "LMT - 000936468" },
    { "text": { "text": "Twitter Inc - TWTR", "type": "plain_text" }, "value": "TWTR - 0001418091" },
    { "text": { "text": "Stratasys Inc - SSYS", "type": "plain_text" }, "value": "SSYS - 000915735" },
    { "text": { "text": "Irobot Corp - IRBT", "type": "plain_text" }, "value": "IRBT - 0001159167" },
    { "text": { "text": "Intuit Inc - INTU", "type": "plain_text" }, "value": "INTU - 000896878" },
    { "text": { "text": "International Business Machines Corp - IBM", "type": "plain_text" }, "value": "IBM - 00051143" },
    { "text": { "text": "Illumina Inc - ILMN", "type": "plain_text" }, "value": "ILMN - 0001110803" },
    { "text": { "text": "Activision Blizzard Inc - ATVI", "type": "plain_text" }, "value": "ATVI - 000718877" },
    { "text": { "text": "Ebay Inc - EBAY", "type": "plain_text" }, "value": "EBAY - 0001065088" },
    { "text": { "text": "Electronic Arts Inc - EA", "type": "plain_text" }, "value": "EA - 000712515" },
    { "text": { "text": "Advanced Micro Devices Inc - AMD", "type": "plain_text" }, "value": "AMD - 0002488" },
    { "text": { "text": "Southwest Airlines Co - LUV", "type": "plain_text" }, "value": "LUV - 00092380" },
    { "text": { "text": "Delta Air Lines Inc - DAL", "type": "plain_text" }, "value": "DAL - 00027904" },
    { "text": { "text": "Hilton Worldwide Holdings Inc - HLT", "type": "plain_text" }, "value": "HLT - 0001585689" },
    { "text": { "text": "Lululemon Athletica Inc - LULU", "type": "plain_text" }, "value": "LULU - 0001397187" },
    { "text": { "text": "Fedex Corp - FDX", "type": "plain_text" }, "value": "FDX - 0001048911" },
    { "text": { "text": "Spirit Airlines Inc - SAVE", "type": "plain_text" }, "value": "SAVE - 0001498710" },
    { "text": { "text": "American Airlines Group Inc - AAL", "type": "plain_text" }, "value": "AAL - 0006201" },
    { "text": { "text": "PayPal Holdings, Inc. - PYPL", "type": "plain_text" }, "value": "PYPL - 0001633917" },
    { "text": { "text": "Tencent Holdings Ltd - TCEHY", "type": "plain_text" }, "value": "TCEHY - 0001293451" },
    { "text": { "text": "Alibaba Group Holding Ltd - BABA", "type": "plain_text" }, "value": "BABA - 0001577552" },
    { "text": { "text": "Snap Inc - SNAP", "type": "plain_text" }, "value": "SNAP - 0001564408" },
    { "text": { "text": "Square, Inc. - SQ", "type": "plain_text" }, "value": "SQ - 0001512673" },
    { "text": { "text": "Zoom Video Communications, Inc. - ZM", "type": "plain_text" }, "value": "ZM - 0001585521" },
    { "text": { "text": "JD.com, Inc. - JD", "type": "plain_text" }, "value": "JD - 0001549802" },
    { "text": { "text": "Airbnb, Inc. - ABNB", "type": "plain_text" }, "value": "ABNB - 0001559720" },
    { "text": { "text": "Snowflake Inc. - SNOW", "type": "plain_text" }, "value": "SNOW - 0001640147" },
    { "text": { "text": "Uber Technologies, Inc - UBER", "type": "plain_text" }, "value": "UBER - 0001543151" },
    { "text": { "text": "Lyft, Inc. - LYFT", "type": "plain_text" }, "value": "LYFT - 0001759509" },
    { "text": { "text": "TWILIO INC - TWLO", "type": "plain_text" }, "value": "TWLO - 0001447669" },
    { "text": { "text": "DoorDash, Inc. - DASH", "type": "plain_text" }, "value": "DASH - 0001792789" },
    { "text": { "text": "DOCUSIGN, INC. - DOCU", "type": "plain_text" }, "value": "DOCU - 0001261333" },
    { "text": { "text": "Roblox Corp - RBLX", "type": "plain_text" }, "value": "RBLX - 0001315098" },
    { "text": { "text": "Palantir Technologies Inc. - PLTR", "type": "plain_text" }, "value": "PLTR - 0001321655" },
    { "text": { "text": "Robinhood Markets, Inc. - HOOD", "type": "plain_text" }, "value": "HOOD - 0001783879" },
    { "text": { "text": "PELOTON INTERACTIVE, INC. - PTON", "type": "plain_text" }, "value": "PTON - 0001639825" },
    { "text": { "text": "Wix.com Ltd. - WIX", "type": "plain_text" }, "value": "WIX - 0001576789" },
    { "text": { "text": "XPENG INC. - XPEV", "type": "plain_text" }, "value": "XPEV - 0001810997" },
    { "text": { "text": "Virgin Galactic Holdings, Inc - SPCE", "type": "plain_text" }, "value": "SPCE - 0001706946" },
    { "text": { "text": "Nikola Corp - NKLA", "type": "plain_text" }, "value": "NKLA - 0001731289" },
    { "text": { "text": "Opendoor Technologies Inc. - OPEN", "type": "plain_text" }, "value": "OPEN - 0001801169" },
    { "text": { "text": "CLOVER HEALTH INVESTMENTS, CORP. /DE - CLOV", "type": "plain_text" }, "value": "CLOV - 0001801170" },
    { "text": { "text": "Social Capital Hedosophia Holdings Corp. IV - IPOD", "type": "plain_text" }, "value": "IPOD - 0001818876" },
    { "text": { "text": "Social Capital Hedosophia Holdings Corp. VI - IPOF", "type": "plain_text" }, "value": "IPOF - 0001818873" },
    { "text": { "text": "SoFi Technologies, Inc. - SOFI", "type": "plain_text" }, "value": "SOFI - 0001818874" },
    { "text": { "text": "Pershing Square Tontine Holdings, Ltd. - PSTH", "type": "plain_text" }, "value": "PSTH - 0001811882" },
    { "text": { "text": "DraftKings Inc. - DKNG", "type": "plain_text" }, "value": "DKNG - 0001772757" },
    { "text": { "text": "SoFi Technologies, Inc. - SOFI", "type": "plain_text" }, "value": "SOFI - 0001818874" },
    { "text": { "text": "Social Capital Suvretta Holdings Corp. I - DNAA", "type": "plain_text" }, "value": "DNAA - 0001850266" },
    { "text": { "text": "Social Capital Suvretta Holdings Corp. II - DNAB", "type": "plain_text" }, "value": "DNAB - 0001850271" },
    { "text": { "text": "Social Capital Suvretta Holdings Corp. III - DNAC", "type": "plain_text" }, "value": "DNAC - 0001850270" },
    { "text": { "text": "Social Capital Suvretta Holdings Corp. IV - DNAD", "type": "plain_text" }, "value": "DNAD - 0001850272" },
    { "text": { "text": "Khosla Ventures Acquisition Co. II - KVSB", "type": "plain_text" }, "value": "KVSB - 0001846069" },
    { "text": { "text": "Khosla Ventures Acquisition Co. III - KVSC", "type": "plain_text" }, "value": "KVSC - 0001846068" },
    # COMPANIES BELOW ARE TEST MENU ITEMS:
    { "text": { "text": "SIMPLICITY ESPORTS & GAMING Co - S", "type": "plain_text" }, "value": "LONE - 0001661920" },
    { "text": { "text": "Lightning eMotors, Inc. - ZEV", "type": "plain_text" }, "value": "ZEV - 0001802749" },
    { "text": { "text": "Tesla Motors Inc - TSLA", "type": "plain_text" }, "value": "TSLA - 0001318605" },
]

